(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(elfeed-feeds
   '("https://www.youtube.com/feeds/videos.xml?channel_id=UCTpmmkp1E4nmZqWPS-dl5bg"
     ("http://www.youtube.com/channel/UCzwCEE_PchiBULMnAJqhGVg" nonfocus)
     ("http://www.youtube.com/channel/UCzWQYUVCpZqtN93H8RR44Qw" nonfocus)
     ("http://www.youtube.com/channel/UCzTo99HAs-u0PLTKF_TLkgg" nonfocus)
     ("http://www.youtube.com/channel/UCzQUP1qoWDoEbmsQxvdjxgQ" nonfocus)
     ("http://www.youtube.com/channel/UCzNTVzprq6UG7kBK0LIDtUw" nonfocus)
     ("http://www.youtube.com/channel/UCzL_0nIe8B4-7ShhVPfJkgw" nonfocus)
     ("http://www.youtube.com/channel/UCz4a7agVFr1TxU-mpAP8hkw" nonfocus)
     ("http://www.youtube.com/channel/UCz22l7kbce-uFJAoaZqxD1A" nonfocus)
     ("http://www.youtube.com/channel/UCyzf9_LUFN-2Xr30z8hyW1A" nonfocus)
     ("http://www.youtube.com/channel/UCydShVfAub9TSmL1N4BTlGQ" nonfocus)
     ("http://www.youtube.com/channel/UCybBViio_TH_uiFFDJuz5tg" nonfocus)
     ("http://www.youtube.com/channel/UCyHta2dyCTkf29AB67AYn7A" nonfocus)
     ("http://www.youtube.com/channel/UCy48CHOjMNRFoEQqYN1GbBQ" nonfocus)
     ("http://www.youtube.com/channel/UCxoQaZS8YdKkyfBwGZay-Xg" nonfocus)
     ("http://www.youtube.com/channel/UCxneJBWWNLs-A6ckls1Rrug" nonfocus)
     ("http://www.youtube.com/channel/UCxX9wt5FWQUAAz4UrysqK9A" nonfocus)
     ("http://www.youtube.com/channel/UCx8Z14PpntdaxCt2hakbQLQ" nonfocus)
     ("http://www.youtube.com/channel/UCwqwIBBMeV23J6mBuuNd-aA" nonfocus)
     ("http://www.youtube.com/channel/UCwobzUc3z-0PrFpoRxNszXQ" nonfocus)
     ("http://www.youtube.com/channel/UCwWhde0527ab8MrlTFXxvIA" nonfocus)
     ("http://www.youtube.com/channel/UCwOP4nv1jdcnDzBSRfc7Hjg" nonfocus)
     ("http://www.youtube.com/channel/UCwF59EqBxrPUphvR0X0SQ4g" nonfocus)
     ("http://www.youtube.com/channel/UCwB7HrnRlOfasrbCJoiZ9Lg" nonfocus)
     ("http://www.youtube.com/channel/UCwB3HiWejAkml1UZ0Qo2bFg" nonfocus)
     ("http://www.youtube.com/channel/UCw-kH-Od73XDAt7qtH9uBYA" nonfocus)
     ("http://www.youtube.com/channel/UCvpDeGlR5wLP9Z3Tb6K0Xfg" nonfocus)
     ("http://www.youtube.com/channel/UCvnnHnUaf-Ye7AW9azojwpw" nonfocus)
     ("http://www.youtube.com/channel/UCvSM87j1um-606TMhbA_kkQ" nonfocus)
     ("http://www.youtube.com/channel/UCvQECJukTDE2i6aCoMnS-Vg" nonfocus)
     ("http://www.youtube.com/channel/UCvPBwFtlth679NMXM2jsxlg" nonfocus)
     ("http://www.youtube.com/channel/UCvJ2c71Xz8BgfLwg-r82Dng" nonfocus)
     ("http://www.youtube.com/channel/UCvBqzzvUBLCs8Y7Axb-jZew" nonfocus)
     ("http://www.youtube.com/channel/UCuv3IZ2RpS657pt5aL7TVtQ" nonfocus)
     ("http://www.youtube.com/channel/UCutCcajxhR33k9UR-DdLsAQ" nonfocus)
     ("http://www.youtube.com/channel/UCurYxozQbvKn-oNUxNJh45Q" nonfocus)
     ("http://www.youtube.com/channel/UCuloVcv1tLjHxTek2avscTg" nonfocus)
     ("http://www.youtube.com/channel/UCuZB9Av85ppUdX6Yh_QH0pA" nonfocus)
     ("http://www.youtube.com/channel/UCuT4ofSEmnVwHpWVP-pUzug" nonfocus)
     ("http://www.youtube.com/channel/UCtxCXg-UvSnTKPOzLH4wJaQ" nonfocus)
     ("http://www.youtube.com/channel/UCtwEIq8U94Hnd-A0kl5GkZA" nonfocus)
     ("http://www.youtube.com/channel/UCtslD4DGH6PKyG_1gFAX7sg" nonfocus)
     ("http://www.youtube.com/channel/UCtYzVCmNxrshH4_bPO_-Y-A" nonfocus)
     ("http://www.youtube.com/channel/UCtYLUTtgS3k1Fg4y5tAhLbw" nonfocus)
     ("http://www.youtube.com/channel/UCtVkW6Uytu_9rOgTq5Adcjw" nonfocus)
     ("http://www.youtube.com/channel/UCtUAQxOgWIPbN9XYzJ4dRGw" nonfocus)
     ("http://www.youtube.com/channel/UCtI0Hodo5o5dUb67FeUjDeA" nonfocus)
     ("http://www.youtube.com/channel/UCsvqVGtbbyHaMoevxPAq9Fg" nonfocus)
     ("http://www.youtube.com/channel/UCsdJxGA27BSz7IiPMn9VV1g" nonfocus)
     ("http://www.youtube.com/channel/UCs_tLP3AiwYKwdUHpltJPuA" nonfocus)
     ("http://www.youtube.com/channel/UCs_6DXZROU29pLvgQdCx4Ww" nonfocus)
     ("http://www.youtube.com/channel/UCsXVk37bltHxD1rDPwtNM8Q" nonfocus)
     ("http://www.youtube.com/channel/UCsT0YIqwnpJCM-mx7-gSA4Q" nonfocus)
     ("http://www.youtube.com/channel/UCsHbJuyHI7eKje1AH_joWyQ" nonfocus)
     ("http://www.youtube.com/channel/UCsBjURrPoezykLs9EqgamOA" nonfocus)
     ("http://www.youtube.com/channel/UCsBKTrp45lTfHa_p49I2AEQ" nonfocus)
     ("http://www.youtube.com/channel/UCrzyJYtjLOTfnUur8hsr7ow" nonfocus)
     ("http://www.youtube.com/channel/UCrcKqsixyf2lqkM_ITGPq1A" nonfocus)
     ("http://www.youtube.com/channel/UCraiFqWi0qSIxXxXN4IHFBQ" nonfocus)
     ("http://www.youtube.com/channel/UCrXM4HqK9th3E2a04Z9Lh-Q" nonfocus)
     ("http://www.youtube.com/channel/UCrM7B7SL_g1edFOnmj-SDKg" nonfocus)
     ("http://www.youtube.com/channel/UCrIqYP0lBVMxbX9mbRs6Avw" nonfocus)
     ("http://www.youtube.com/channel/UCrC8mOqJQpoB7NuIMKIS6rQ" nonfocus)
     ("http://www.youtube.com/channel/UCqvaXJ1K3HheTPNjH-KpwXQ" nonfocus)
     ("http://www.youtube.com/channel/UCqvXjWmqoezhHv-SSq1p85g" nonfocus)
     ("http://www.youtube.com/channel/UCqXCX2DnQZh8e4VNT7MPTtA" nonfocus)
     ("http://www.youtube.com/channel/UCqPbJJw1gQZqGFFb9hwBmBA" nonfocus)
     ("http://www.youtube.com/channel/UCqJpNJWr12KKghP2o0O87Qg" nonfocus)
     ("http://www.youtube.com/channel/UCqFg6QnwgtVHo1iFgpxrx-A" nonfocus)
     ("http://www.youtube.com/channel/UCqECaJ8Gagnn7YCbPEzWH6g" nonfocus)
     ("http://www.youtube.com/channel/UCpzmNj9lwp7hyUPBjZa7rUw" nonfocus)
     ("http://www.youtube.com/channel/UCpZ5qUqpW4hW4zdfuBxMSJA" nonfocus)
     ("http://www.youtube.com/channel/UCpLfM1_MIcIQ3jweRT19LVw" nonfocus)
     ("http://www.youtube.com/channel/UCpJmKq_w53t_uDCw_Dzpc1A" nonfocus)
     ("http://www.youtube.com/channel/UCpFFItkfZz1qz5PpHpqzYBw" nonfocus)
     ("http://www.youtube.com/channel/UCpExuV8qJMfCaSQNL1YG6bQ" nonfocus)
     ("http://www.youtube.com/channel/UCpDabn1_Lmq4xcOIfDDjihg" nonfocus)
     ("http://www.youtube.com/channel/UCpCSAcbqs-sjEVfk_hMfY9w" nonfocus)
     ("http://www.youtube.com/channel/UCoyvLy31Ov7QX-KIcWTgwWA" nonfocus)
     ("http://www.youtube.com/channel/UCogasD4DFxmshrBNnJNFcvg" nonfocus)
     ("http://www.youtube.com/channel/UCobgOt3poNKlml3Y5TnVU8Q" nonfocus)
     ("http://www.youtube.com/channel/UCoWhIOUIUCeMxJw4XVbI_6A" nonfocus)
     ("http://www.youtube.com/channel/UCoOae5nYA7VqaXzerajD0lg" nonfocus)
     ("http://www.youtube.com/channel/UCoO0dEKzlfCbaJO_hY7qbxQ" nonfocus)
     ("http://www.youtube.com/channel/UCo8bcnLyZH8tBIH9V1mLgqQ" nonfocus)
     ("http://www.youtube.com/channel/UCo7a6riBFJ3tkeHjvkXPn1g" nonfocus)
     ("http://www.youtube.com/channel/UCnyQy0wD_LCZTlyFHnKIS7Q" nonfocus)
     ("http://www.youtube.com/channel/UCnxrdFPXJMeHru_b4Q_vTPQ" nonfocus)
     ("http://www.youtube.com/channel/UCnpekFV93kB1O0rVqEKSumg" nonfocus)
     ("http://www.youtube.com/channel/UCnnkuzisIk9qvhRBCP_jG9Q" nonfocus)
     ("http://www.youtube.com/channel/UCnmGIkw-KdI0W5siakKPKog" nonfocus)
     ("http://www.youtube.com/channel/UCneQdPbDLwZ__ZXP0YVwiag" nonfocus)
     ("http://www.youtube.com/channel/UCnM02drQP-dF7WMgtJHR4Xw" nonfocus)
     ("http://www.youtube.com/channel/UCn8zNIfYAQNdrFRrr8oibKw" nonfocus)
     ("http://www.youtube.com/channel/UCn1XnDWhsLS5URXTi5wtFTA" nonfocus)
     ("http://www.youtube.com/channel/UCmnEsLQNA0P-t541TmQAdFA" nonfocus)
     ("http://www.youtube.com/channel/UCm_WkN0wg49-eG4SymAQ_4g" nonfocus)
     ("http://www.youtube.com/channel/UCmParc4a14EKrENcME-9OOA" nonfocus)
     ("http://www.youtube.com/channel/UCmP5H2rF-ER33a58ZD5jCig" nonfocus)
     ("http://www.youtube.com/channel/UCmL1WlDI8UkXDXCXcBQN9CA" nonfocus)
     ("http://www.youtube.com/channel/UCmJ0PllyWR_cQaEBBIJil9w" nonfocus)
     ("http://www.youtube.com/channel/UCmHsFMZuAoVragN5sCQLnVw" nonfocus)
     ("http://www.youtube.com/channel/UCmGhrrFgqXZfSSt7UKQ0LFQ" nonfocus)
     ("http://www.youtube.com/channel/UCmGSJVG3mCRXVOP4yZrU1Dw" nonfocus)
     ("http://www.youtube.com/channel/UCmEW4_Y9oJaG5sA2YVIXreg" nonfocus)
     ("http://www.youtube.com/channel/UCm5mt-A4w61lknZ9lCsZtBw" nonfocus)
     ("http://www.youtube.com/channel/UClfEht64_NrzHf8Y0slKEjw" nonfocus)
     ("http://www.youtube.com/channel/UClb90NQQcskPUGDIXsQEz5Q" nonfocus)
     ("http://www.youtube.com/channel/UClUDTB6EJvzP7eY5Wgl4lRw" nonfocus)
     ("http://www.youtube.com/channel/UClOghZ_xkI1km31IeoY-9Bw" nonfocus)
     ("http://www.youtube.com/channel/UClLZ2KIEW9s7HL5l6fqjMBA" nonfocus)
     ("http://www.youtube.com/channel/UClFO6ULKU2XXQ_zb76JMUPQ" nonfocus)
     ("http://www.youtube.com/channel/UCkw4JCwteGrDHIsyIIKo4tQ" nonfocus)
     ("http://www.youtube.com/channel/UCk8n46m74K5XWfdeBzOXDfA" nonfocus)
     ("http://www.youtube.com/channel/UCk76m6xBD0pQVGl6dPbTbPg" nonfocus)
     ("http://www.youtube.com/channel/UCk3vAQoPPXpYdnyqpV7kx7w" nonfocus)
     ("http://www.youtube.com/channel/UCj_QArtDR7zzHY2WgmXBUbw" nonfocus)
     ("http://www.youtube.com/channel/UCj_1aKD4pxBCWKwf69tl0SQ" nonfocus)
     ("http://www.youtube.com/channel/UCjGBpHPmVf8MHo_LkKM8wtg" nonfocus)
     ("http://www.youtube.com/channel/UCj7v9UM1aGx6GR-nsY-9u8w" nonfocus)
     ("http://www.youtube.com/channel/UCiz26UeGvcTy4_M3Zhgk7FQ" nonfocus)
     ("http://www.youtube.com/channel/UCiq1FIgtEK7LRAOB1JXTPig" nonfocus)
     ("http://www.youtube.com/channel/UCilFG-3J1waFv6dlyKxwvxQ" nonfocus)
     ("http://www.youtube.com/channel/UCiTjCIT_9EXV1Wp1cY0zaUA" nonfocus)
     ("http://www.youtube.com/channel/UCiT9RITQ9PW6BhXK0y2jaeg" nonfocus)
     ("http://www.youtube.com/channel/UCiApy-F_Y1bJQRY7LE8ixAw" nonfocus)
     ("http://www.youtube.com/channel/UChwksNT6DWt7jrRCV9F0qGg" nonfocus)
     ("http://www.youtube.com/channel/UCh_dVD10YuSghle8g6yjePg" nonfocus)
     ("http://www.youtube.com/channel/UChYs-_zjKRYhdMddjx-NPLw" nonfocus)
     ("http://www.youtube.com/channel/UCh9nVJoWXmFb7sLApWGcLPQ" nonfocus)
     ("http://www.youtube.com/channel/UCh8IuVJvRdporrHi-I9H7Vw" nonfocus)
     ("http://www.youtube.com/channel/UCgnTNj3QFz7gJ18lMGmf4Ow" nonfocus)
     ("http://www.youtube.com/channel/UCgiYnY9qh-PAM801gCK8XUg" nonfocus)
     ("http://www.youtube.com/channel/UCgRvm1yLFoaQKhmaTqXk9SA" nonfocus)
     ("http://www.youtube.com/channel/UCgPrg8qyvKaiED9tvdAIfpQ" nonfocus)
     ("http://www.youtube.com/channel/UCgNg3vwj3xt7QOrcIDaHdFg" nonfocus)
     ("http://www.youtube.com/channel/UCgI26KNITusiGOFL6MLz_8Q" nonfocus)
     ("http://www.youtube.com/channel/UCgBncpylJ1kiVaPyP-PZauQ" nonfocus)
     ("http://www.youtube.com/channel/UCfzlCWGWYyIQ0aLC5w48gBQ" nonfocus)
     ("http://www.youtube.com/channel/UCfzOLBT7jyHFcaTgwmnttog" nonfocus)
     ("http://www.youtube.com/channel/UCfw2hvuj40AChU7n-N-PRHA" nonfocus)
     ("http://www.youtube.com/channel/UCfhbydY40P2Lli9HuBz8cdA" nonfocus)
     ("http://www.youtube.com/channel/UCffs9TWLuHnZpKJwrHGuYVw" nonfocus)
     ("http://www.youtube.com/channel/UCfM3zsQsOnfWNUppiycmBuw" nonfocus)
     ("http://www.youtube.com/channel/UCf0WB91t8Ky6AuYcQV0CcLw" nonfocus)
     ("http://www.youtube.com/channel/UCeVMnSShP_Iviwkknt83cww" nonfocus)
     ("http://www.youtube.com/channel/UCeKrthyRHDef1ewuHSGLX-A" nonfocus)
     ("http://www.youtube.com/channel/UCdsOTr6SmDrxuWE7sJFrkhQ" nonfocus)
     ("http://www.youtube.com/channel/UCdngmbVKX1Tgre699-XLlUA" nonfocus)
     ("http://www.youtube.com/channel/UCdlNK1xcy-Sn8liq7feNxWw" nonfocus)
     ("http://www.youtube.com/channel/UCddiUEpeqJcYeBxX1IVBKvQ" nonfocus)
     ("http://www.youtube.com/channel/UCdKG2JnvPu6mY1NDXYFfN0g" nonfocus)
     ("http://www.youtube.com/channel/UCd6Za0CXVldhY8fK8eYoIuw" nonfocus)
     ("http://www.youtube.com/channel/UCd61H807LGfGXnsXpxwaBNA" nonfocus)
     ("http://www.youtube.com/channel/UCd0dc7kQA1FUpJ76o1EjLqQ" nonfocus)
     ("http://www.youtube.com/channel/UCd-ac3z3CdHBcJwrNTfRplQ" nonfocus)
     ("http://www.youtube.com/channel/UCcu0BTMzf6vYhfSVAECmR4Q" nonfocus)
     ("http://www.youtube.com/channel/UCctXZhXmG-kf3tlIXgVZUlw" nonfocus)
     ("http://www.youtube.com/channel/UCclfz6zVWWOpsQsg3OheI3g" nonfocus)
     ("http://www.youtube.com/channel/UCciB8y9GdQvY3QbcH6hLN2w" nonfocus)
     ("http://www.youtube.com/channel/UCcefcZRL2oaA_uBNeo5UOWg" nonfocus)
     ("http://www.youtube.com/channel/UCcabW7890RKJzL968QWEykA" nonfocus)
     ("http://www.youtube.com/channel/UCcL78rRNuUQ8t7Dx4CLmRqA" nonfocus)
     ("http://www.youtube.com/channel/UCcIXc5mJsHVYTZR1maL5l9w" nonfocus)
     ("http://www.youtube.com/channel/UCbojg-FJgI1L6iLWUzgcsww" nonfocus)
     ("http://www.youtube.com/channel/UCbj1uYp-Z_YjyU4fQ0OYDCg" nonfocus)
     ("http://www.youtube.com/channel/UCbfYPyITQ-7l4upoX8nvctg" nonfocus)
     ("http://www.youtube.com/channel/UCbbQalJ4OaC0oQ0AqRaOJ9g" nonfocus)
     ("http://www.youtube.com/channel/UCbPI6xmFQaMH0jlm9aKFOwA" nonfocus)
     ("http://www.youtube.com/channel/UCbOX--VOebPe-MMRkatFRxw" nonfocus)
     ("http://www.youtube.com/channel/UCbIbeVkqM0_FReT5o7FFnQg" nonfocus)
     ("http://www.youtube.com/channel/UCamLstJyCa-t5gfZegxsFMw" nonfocus)
     ("http://www.youtube.com/channel/UCagiBBx1prefrlsDzDxuA9A" nonfocus)
     ("http://www.youtube.com/channel/UCaf8ut2dP0w08kKw-jPXx5Q" nonfocus)
     ("http://www.youtube.com/channel/UCaYvVQcC-Zk8EFtuTVnp_xg" nonfocus)
     ("http://www.youtube.com/channel/UCaPX53JLxxSbwZz_Ra_cL0g" nonfocus)
     ("http://www.youtube.com/channel/UCaKZDEMDdQc8t6GzFj1_TDw" nonfocus)
     ("http://www.youtube.com/channel/UCa6cLayR1jdfGFPEOXKCRYg" nonfocus)
     ("http://www.youtube.com/channel/UCa6Sl0jhPyEgkWVU43pVDgg" nonfocus)
     ("http://www.youtube.com/channel/UC_tXTJZPwodoYXN6MVpBYgg" nonfocus)
     ("http://www.youtube.com/channel/UC_s0g4QdprLkyyN2MDpef7Q" nonfocus)
     ("http://www.youtube.com/channel/UC_mYaQAE6-71rjSN6CeCA-g" nonfocus)
     ("http://www.youtube.com/channel/UC_hG9fglfmShkwex1KVydHA" nonfocus)
     ("http://www.youtube.com/channel/UC_evcfxhjjui5hChhLE08tQ" nonfocus)
     ("http://www.youtube.com/channel/UC_E4px0RST-qFwXLJWBav8Q" nonfocus)
     ("http://www.youtube.com/channel/UC_AsppHdP-dg92u8M8Oh4yg" nonfocus)
     ("http://www.youtube.com/channel/UCZuKpNyipL9W-OkKwCMwVNQ" nonfocus)
     ("http://www.youtube.com/channel/UCZnDGbpYy9NJe99pf7w7BTw" nonfocus)
     ("http://www.youtube.com/channel/UCZkr1DYHWiWZ59ARUWfF5qA" nonfocus)
     ("http://www.youtube.com/channel/UCZiL6BoryLWxyapUuVYW27g" nonfocus)
     ("http://www.youtube.com/channel/UCZg2-TZBGrwRbuettVf10uw" nonfocus)
     ("http://www.youtube.com/channel/UCZbKwSM00cPCNCdJ-ClfqFQ" nonfocus)
     ("http://www.youtube.com/channel/UCZYTClx2T1of7BRZ86-8fow" nonfocus)
     ("http://www.youtube.com/channel/UCZOVpBV7YHnjZCETwEhCWnA" nonfocus)
     ("http://www.youtube.com/channel/UCZHmQk67mSJgfCCTn7xBfew" nonfocus)
     ("http://www.youtube.com/channel/UCZEfiXy7PmtVTezYUvc4zZw" nonfocus)
     ("http://www.youtube.com/channel/UCZCFT11CWBi3MHNlGf019nw" nonfocus)
     ("http://www.youtube.com/channel/UCZ7x7yDBbEFCGztD8BYvRhA" nonfocus)
     ("http://www.youtube.com/channel/UCZ4AMrDcNrfy3X6nsU8-rPg" nonfocus)
     ("http://www.youtube.com/channel/UCYyaQsm2HyneP9CsIOdihBw" nonfocus)
     ("http://www.youtube.com/channel/UCYt1sfh5464XaDBH0oH_o7Q" nonfocus)
     ("http://www.youtube.com/channel/UCYpBgT4riB-VpsBBBQkblqQ" nonfocus)
     ("http://www.youtube.com/channel/UCYgGfqfb9c3AOGJqxqdjNYw" nonfocus)
     ("http://www.youtube.com/channel/UCYeF244yNGuFefuFKqxIAXw" nonfocus)
     ("http://www.youtube.com/channel/UCYS9sTrPpcIVDxz2yVPbuLw" nonfocus)
     ("http://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw" nonfocus)
     ("http://www.youtube.com/channel/UCYJLdSmyKoXCbnd-pklMn5Q" nonfocus)
     ("http://www.youtube.com/channel/UCY6N8zZhs2V7gNTUxPuKWoQ" nonfocus)
     ("http://www.youtube.com/channel/UCY1kMZp36IQSyNx_9h4mpCg" nonfocus)
     ("http://www.youtube.com/channel/UCY0fMuXKDGm3iwJZyTb_-yA" nonfocus)
     ("http://www.youtube.com/channel/UCXuO_AmrcE16fDoNiq9JZZg" nonfocus)
     ("http://www.youtube.com/channel/UCXgGY0wkgOzynnHvSEVmE3A" nonfocus)
     ("http://www.youtube.com/channel/UCX_7hEUHZCQhQI8oqHPsr0g" nonfocus)
     ("http://www.youtube.com/channel/UCXZCJLdBC09xxGZ6gcdrc6A" nonfocus)
     ("http://www.youtube.com/channel/UCXN-nIyaBuR-1qpas1P-CGA" nonfocus)
     ("http://www.youtube.com/channel/UCXAWX5r69jcqPTNAhXCSA7Q" nonfocus)
     ("http://www.youtube.com/channel/UCXAEisvouf1Tp5fuoKJUrgw" nonfocus)
     ("http://www.youtube.com/channel/UCX6b17PVsYBQ0ip5gyeme-Q" nonfocus)
     ("http://www.youtube.com/channel/UCX6OQ3DkcsbYNE6H8uQQuVA" nonfocus)
     ("http://www.youtube.com/channel/UCWxBHtvU9Uh1AqX7-96GmTg" nonfocus)
     ("http://www.youtube.com/channel/UCWrXlzhIENTJrAuKVuPgdEA" nonfocus)
     ("http://www.youtube.com/channel/UCWXI5YeOsh03QvJ59PMaXFw" nonfocus)
     ("http://www.youtube.com/channel/UCWN3xxRkmTPmbKwht9FuE5A" nonfocus)
     ("http://www.youtube.com/channel/UCWA1k1HggNlY8UDmBYT1W0Q" nonfocus)
     ("http://www.youtube.com/channel/UCW4OkAZwGC0xOmqd77FKWsw" nonfocus)
     ("http://www.youtube.com/channel/UCW1bFNsNnwsx4jTg9xFoPpw" nonfocus)
     ("http://www.youtube.com/channel/UCW-l49hIAqEltHb37JdQ0Ig" nonfocus)
     ("http://www.youtube.com/channel/UCVt9rN2LzKzNwJG-VXvZGkA" nonfocus)
     ("http://www.youtube.com/channel/UCVrG0AsRMb0pPcxzX75SusA" nonfocus)
     ("http://www.youtube.com/channel/UCVSjGPj-4suXOrW42dMkrrQ" nonfocus)
     ("http://www.youtube.com/channel/UCVOTBwF0vnSxMRIbfSE_K_g" nonfocus)
     ("http://www.youtube.com/channel/UCU_W0oE_ock8bWKjALiGs8Q" nonfocus)
     ("http://www.youtube.com/channel/UCUWbS9qoyLKTdOlvgK1GBlA" nonfocus)
     ("http://www.youtube.com/channel/UCUMccND2H_CVS0dMZKCPCXA" nonfocus)
     ("http://www.youtube.com/channel/UCUHH1qFPr7nUzpMQhIV_DzQ" nonfocus)
     ("http://www.youtube.com/channel/UCTzjnbxgPIHYD0_qDBvNOSQ" nonfocus)
     ("http://www.youtube.com/channel/UCTt7pyY-o0eltq14glaG5dg" nonfocus)
     ("http://www.youtube.com/channel/UCTpmmkp1E4nmZqWPS-dl5bg" nonfocus)
     ("http://www.youtube.com/channel/UCToe3dspZyw2L_JY-JmP3Mw" nonfocus)
     ("http://www.youtube.com/channel/UCTHqt-KLjsABkr7OAHOWU7g" nonfocus)
     ("http://www.youtube.com/channel/UCT0dmfFCLWuVKPWZ6wcdKyg" nonfocus)
     ("http://www.youtube.com/channel/UCSzIJD3pa5w3thnawk43rQQ" nonfocus)
     ("http://www.youtube.com/channel/UCSqetNaur-z6CU9EdTV0GPw" nonfocus)
     ("http://www.youtube.com/channel/UCSq7P1DVsfkdCNwc5BYh6iQ" nonfocus)
     ("http://www.youtube.com/channel/UCSNeZleDn9c74yQc-EKnVTA" nonfocus)
     ("http://www.youtube.com/channel/UCSL0Oa4E6HG4g3Qsh3hDCMw" nonfocus)
     ("http://www.youtube.com/channel/UCSHZKyawb77ixDdsGog4iWA" nonfocus)
     ("http://www.youtube.com/channel/UCS2v3pmmpwcD0PWPwf65Zmw" nonfocus)
     ("http://www.youtube.com/channel/UCS0s6BFzIcvC2gTH52_vBEA" nonfocus)
     ("http://www.youtube.com/channel/UCRzYN32xtBf3Yxsx5BvJWJw" nonfocus)
     ("http://www.youtube.com/channel/UCRcgy6GzDeccI7dkbbBna3Q" nonfocus)
     ("http://www.youtube.com/channel/UCRXRbi80k0_vcIfgpOSerTg" nonfocus)
     ("http://www.youtube.com/channel/UCRRr_xrOm66qaigIbwFLvbQ" nonfocus)
     ("http://www.youtube.com/channel/UCRQebyNJm9YRyO5h0eWEVhw" nonfocus)
     ("http://www.youtube.com/channel/UCRPMAqdtSgd0Ipeef7iFsKw" nonfocus)
     ("http://www.youtube.com/channel/UCRLEADhMcb8WUdnQ5_Alk7g" nonfocus)
     ("http://www.youtube.com/channel/UCREgA-BmOocJ9Is_bZV6aJQ" nonfocus)
     ("http://www.youtube.com/channel/UCREFp3D_n8JfcDonlm7Mpyw" nonfocus)
     ("http://www.youtube.com/channel/UCRCdl2SXma02BG384RuZPqg" nonfocus)
     ("http://www.youtube.com/channel/UCR1IuLEqb6UEA_zQ81kwXfg" nonfocus)
     ("http://www.youtube.com/channel/UCR1-GEpyOPzT2AO4D_eifdw" nonfocus)
     ("http://www.youtube.com/channel/UCR-foyF-C6VuAlwy3KZMkgA" nonfocus)
     ("http://www.youtube.com/channel/UCQzHhoWHxmRS07TFx2D7lpQ" nonfocus)
     ("http://www.youtube.com/channel/UCQad3ntruLqx8ppoF5LoUfw" nonfocus)
     ("http://www.youtube.com/channel/UCQYMhOMi_Cdj1CEAU-fv80A" nonfocus)
     ("http://www.youtube.com/channel/UCQVsLdM2pDwvLlZ6Iw2JxVA" nonfocus)
     ("http://www.youtube.com/channel/UCQMLP7H80aUOiBXF-kWLSuA" nonfocus)
     ("http://www.youtube.com/channel/UCQLy6foZbwCp3jw6r-hbaGw" nonfocus)
     ("http://www.youtube.com/channel/UCPxMZIFE856tbTfdkdjzTSQ" nonfocus)
     ("http://www.youtube.com/channel/UCPxA5piFLf-YpW97BN2jAMw" nonfocus)
     ("http://www.youtube.com/channel/UCPpRKDVzdli-TJ2dBNI3wYw" nonfocus)
     ("http://www.youtube.com/channel/UCPmfPl-BsCd3wmE8i45LAoA" nonfocus)
     ("http://www.youtube.com/channel/UCP9YJJ24w6g38VMVMm6Thtg" nonfocus)
     ("http://www.youtube.com/channel/UCP7jMXSY2xbc3KCAE0MHQ-A" nonfocus)
     ("http://www.youtube.com/channel/UCP5tjEmvPItGyLhmjdwP7Ww" nonfocus)
     ("http://www.youtube.com/channel/UCOmcA3f_RrH6b9NmcNa4tdg" nonfocus)
     ("http://www.youtube.com/channel/UCOhHO2ICt0ti9KAh-QHvttQ" nonfocus)
     ("http://www.youtube.com/channel/UCObs0kLIrDjX2LLSybqNaEA" nonfocus)
     ("http://www.youtube.com/channel/UCOSphW_Jjf1E1FoOM1brMGQ" nonfocus)
     ("http://www.youtube.com/channel/UCOGeU-1Fig3rrDjhm9Zs_wg" nonfocus)
     ("http://www.youtube.com/channel/UCO1cgjhGzsSYb1rsB4bFe4Q" nonfocus)
     ("http://www.youtube.com/channel/UCNjPtOCvMrKY5eLwr_-7eUg" nonfocus)
     ("http://www.youtube.com/channel/UCNb4lJHwfk0EKjrDWGq-UEQ" nonfocus)
     ("http://www.youtube.com/channel/UCNU_lfiiWBdtULKOw6X0Dig" nonfocus)
     ("http://www.youtube.com/channel/UCNU2Xe6kr6OJDxWGDXa66gQ" nonfocus)
     ("http://www.youtube.com/channel/UCNIkB2IeJ-6AmZv7bQ1oBYg" nonfocus)
     ("http://www.youtube.com/channel/UCNFGSWVOdVWEe9XJNnfTdyQ" nonfocus)
     ("http://www.youtube.com/channel/UCNANXFnqSRjh5OkORWQ1rbQ" nonfocus)
     ("http://www.youtube.com/channel/UCN9bwVanuGZlAJCrx_quXqQ" nonfocus)
     ("http://www.youtube.com/channel/UCMrRRZxUAXRzjai0SSoFgdw" nonfocus)
     ("http://www.youtube.com/channel/UCMk8U2Hmfdxqn3zrCq2g9oQ" nonfocus)
     ("http://www.youtube.com/channel/UCMSiuCOvFW8tb6WOKXqeZjg" nonfocus)
     ("http://www.youtube.com/channel/UCMDxbhGcsE7EnknxPEzC_Iw" nonfocus)
     ("http://www.youtube.com/channel/UCM3G0qLnOD3NEI2ixgXUi7Q" nonfocus)
     ("http://www.youtube.com/channel/UCM-yUTYGmrNvKOCcAl21g3w" nonfocus)
     ("http://www.youtube.com/channel/UCLkq3HC2y2NPpyQzaeR9slA" nonfocus)
     ("http://www.youtube.com/channel/UCLjMHtCwaTy4aCs-EVudqYQ" nonfocus)
     ("http://www.youtube.com/channel/UCLfxdtB3H0JdnniBnd4DoNA" nonfocus)
     ("http://www.youtube.com/channel/UCLafvi7YIrlSYnd16SXzyPg" nonfocus)
     ("http://www.youtube.com/channel/UCL_v4tC26PvOFytV1_eEVSg" nonfocus)
     ("http://www.youtube.com/channel/UCLER6vZ4sV_RoTG41oEl8zQ" nonfocus)
     ("http://www.youtube.com/channel/UCLB7AzTwc6VFZrBsO2ucBMg" nonfocus)
     ("http://www.youtube.com/channel/UCL8w_A8p8P1HWI3k6PR5Z6w" nonfocus)
     ("http://www.youtube.com/channel/UCL7pUfWNL7NvR2yxwgfw1-w" nonfocus)
     ("http://www.youtube.com/channel/UCL1yMVRMh3vxitPiVaXfkoA" nonfocus)
     ("http://www.youtube.com/channel/UCL1FpHm41Y16oMgUgwuRoyg" nonfocus)
     ("http://www.youtube.com/channel/UCKmkpoEqg1sOMGEiIysP8Tw" nonfocus)
     ("http://www.youtube.com/channel/UCKZozRVHRYsYHGEyNKuhhdA" nonfocus)
     ("http://www.youtube.com/channel/UCKXx22vOENUyHrVAADq7Z_g" nonfocus)
     ("http://www.youtube.com/channel/UCKHVR_boqdcL1az39azGJHA" nonfocus)
     ("http://www.youtube.com/channel/UCK7tptUDHh-RYDsdxO1-5QQ" nonfocus)
     ("http://www.youtube.com/channel/UCJzty8cEWXEOc-b9KuzyBFw" nonfocus)
     ("http://www.youtube.com/channel/UCJm2TgUqtK1_NLBrjNQ1P-w" nonfocus)
     ("http://www.youtube.com/channel/UCJgcDT2XI3cQJhGe01AFaHQ" nonfocus)
     ("http://www.youtube.com/channel/UCJcycnanWtyOGcz34jUlYZA" nonfocus)
     ("http://www.youtube.com/channel/UCJS9pqu9BzkAMNTmzNMNhvg" nonfocus)
     ("http://www.youtube.com/channel/UCJINtWke3-FMz2WuEltWDVQ" nonfocus)
     ("http://www.youtube.com/channel/UCIxc1kU1sH2V8E5ZZktN6Ig" nonfocus)
     ("http://www.youtube.com/channel/UCItJsxqZNWUyxFn-A2tzizQ" nonfocus)
     ("http://www.youtube.com/channel/UCIlU5KDHKFSaebYviKfOidw" nonfocus)
     ("http://www.youtube.com/channel/UCI_7ZLp2k4DJ6zP836wqFbw" nonfocus)
     ("http://www.youtube.com/channel/UCIHdDJ0tjn_3j-FS7s_X1kQ" nonfocus)
     ("http://www.youtube.com/channel/UCHnyfMqiRRG1u-2MsSQLbXA" nonfocus)
     ("http://www.youtube.com/channel/UCHnj59g7jezwTy5GeL8EA_g" nonfocus)
     ("http://www.youtube.com/channel/UCHgI_MItRWEKLX7lKz7Xn0g" nonfocus)
     ("http://www.youtube.com/channel/UCHcHYwBh3LsOjbxqfVMLkVA" nonfocus)
     ("http://www.youtube.com/channel/UCHbEOcFp8s-xarbt3iXOaWg" nonfocus)
     ("http://www.youtube.com/channel/UCHAK6CyegY22Zj2GWrcaIxg" nonfocus)
     ("http://www.youtube.com/channel/UCH4BNI0-FOK2dMXoFtViWHw" nonfocus)
     ("http://www.youtube.com/channel/UCGwuxdEeCf0TIA2RbPOj-8g" nonfocus)
     ("http://www.youtube.com/channel/UCGtbVv_ACgV7difdVZ92NMw" nonfocus)
     ("http://www.youtube.com/channel/UCGkpFfEMF0eMJlh9xXj2lMw" nonfocus)
     ("http://www.youtube.com/channel/UCGdLd_wp5_IoJeDpi2KQP1A" nonfocus)
     ("http://www.youtube.com/channel/UCGctnQUOy0cyYC62IQ_J8JA" nonfocus)
     ("http://www.youtube.com/channel/UCGc7sNPryQ07wHHyaZXnS8Q" nonfocus)
     ("http://www.youtube.com/channel/UCGYlNGlloLLZiAL3zBgbMgQ" nonfocus)
     ("http://www.youtube.com/channel/UCGFAWBWTaxQjgoCcSN1HdSQ" nonfocus)
     ("http://www.youtube.com/channel/UCG-KntY7aVnIGXYEBQvmBAQ" nonfocus)
     ("http://www.youtube.com/channel/UCFuF18MyTt4UdhmwDC4d2lg" nonfocus)
     ("http://www.youtube.com/channel/UCFse7YyLRwIDOg1eGqlDMJA" nonfocus)
     ("http://www.youtube.com/channel/UCFJPdVHPZOYhSyxmX_C_Pew" nonfocus)
     ("http://www.youtube.com/channel/UCFFbwnve3yF62-tVXkTyHqg" nonfocus)
     ("http://www.youtube.com/channel/UCEsAG-_-1n9anxCl_ns_xPg" nonfocus)
     ("http://www.youtube.com/channel/UCEdcgjfC2yZfRrX0Y2yW0hQ" nonfocus)
     ("http://www.youtube.com/channel/UCE_M8A5yxnLfW0KghEeajjw" nonfocus)
     ("http://www.youtube.com/channel/UCEWpbFLzoYGPfuWUMFPSaoA" nonfocus)
     ("http://www.youtube.com/channel/UCEPm8QBiVAJArvL7N4BtpsA" nonfocus)
     ("http://www.youtube.com/channel/UCENRvVys9nMpQpENGeL8NEg" nonfocus)
     ("http://www.youtube.com/channel/UCEBb1b_L6zDS3xTUrIALZOw" nonfocus)
     ("http://www.youtube.com/channel/UCEAAzv2OBqxsSczKJ2QZyGQ" nonfocus)
     ("http://www.youtube.com/channel/UCE4Gn00XZbpWvGUfIslT-tA" nonfocus)
     ("http://www.youtube.com/channel/UCE-SaKbJi9J9qIgBaSGfnfQ" nonfocus)
     ("http://www.youtube.com/channel/UCDwLb8FClxNiMa7w6dCO7PQ" nonfocus)
     ("http://www.youtube.com/channel/UCDfCAienRzwXYa2HrfQmdhg" nonfocus)
     ("http://www.youtube.com/channel/UCDei-kUh0R27ygGfdR8Mk9g" nonfocus)
     ("http://www.youtube.com/channel/UCD_r9JOkcN5ZXO94N3X9yTw" nonfocus)
     ("http://www.youtube.com/channel/UCDHao9FxNRHw1VyLuGXI_rA" nonfocus)
     ("http://www.youtube.com/channel/UCCktnahuRFYIBtNnKT5IYyg" nonfocus)
     ("http://www.youtube.com/channel/UCCezIgC97PvUuR4_gbFUs5g" nonfocus)
     ("http://www.youtube.com/channel/UCCYR9GpcE3skVnyMU8Wx1kQ" nonfocus)
     ("http://www.youtube.com/channel/UCCJsQKOKArvDksacfT2ryQw" nonfocus)
     ("http://www.youtube.com/channel/UCC69dxCZQB9VURlHQ8wesPA" nonfocus)
     ("http://www.youtube.com/channel/UCC552Sd-3nyi_tk2BudLUzA" nonfocus)
     ("http://www.youtube.com/channel/UCBwmMxybNva6P_5VmxjzwqA" nonfocus)
     ("http://www.youtube.com/channel/UCBuMwlP7kHkNxdPAqtFSJTw" nonfocus)
     ("http://www.youtube.com/channel/UCBpxspUNl1Th33XbugiHJzw" nonfocus)
     ("http://www.youtube.com/channel/UCBgaV1AaT5h9dy_XHbZhhKA" nonfocus)
     ("http://www.youtube.com/channel/UCBeV1MXmOGBMPT-azuBAiYw" nonfocus)
     ("http://www.youtube.com/channel/UCBa5G_ESCn8Yd4vw5U-gIcg" nonfocus)
     ("http://www.youtube.com/channel/UCBWp-UuN3oN4hGlNFhgAjjg" nonfocus)
     ("http://www.youtube.com/channel/UCBPRJjIWfyNG4X-CRbnv78A" nonfocus)
     ("http://www.youtube.com/channel/UCBMSs6p64AjcHPUBcKU3pfg" nonfocus)
     ("http://www.youtube.com/channel/UCBJycsmduvYEL83R_U4JriQ" nonfocus)
     ("http://www.youtube.com/channel/UCBCDvxfFwRDO3Swl972IHQg" nonfocus)
     ("http://www.youtube.com/channel/UCAvCL8hyXjSUHKEGuUPr1BA" nonfocus)
     ("http://www.youtube.com/channel/UCAuUUnT6oDeKwE6v1NGQxug" nonfocus)
     ("http://www.youtube.com/channel/UCAr_Ev0xCWf3iuag9KWuvLw" nonfocus)
     ("http://www.youtube.com/channel/UCAM35Xuk2-GM4Mb8g0MGSZw" nonfocus)
     ("http://www.youtube.com/channel/UCAE392C3hYv6oLIkkjsaUWw" nonfocus)
     ("http://www.youtube.com/channel/UC9yKfHPA_AKfMiqtG4tvKPw" nonfocus)
     ("http://www.youtube.com/channel/UC9pxOEHrjsl7YKBSc7sl_KQ" nonfocus)
     ("http://www.youtube.com/channel/UC9p_wQs8b8SHvfJSuuxEnvw" nonfocus)
     ("http://www.youtube.com/channel/UC9iMriYmer476o8BttUoF3A" nonfocus)
     ("http://www.youtube.com/channel/UC9WQRw8jgJhag-vkDNTDMRg" nonfocus)
     ("http://www.youtube.com/channel/UC9RM-iSvTu1uPJb8X5yp3EQ" nonfocus)
     ("http://www.youtube.com/channel/UC9OeZkIwhzfv-_Cb7fCikLQ" nonfocus)
     ("http://www.youtube.com/channel/UC9Ep0Y4T5rvUuIfjKN1wqTw" nonfocus)
     ("http://www.youtube.com/channel/UC90F0i80IZEHqm6PCAHk1BQ" nonfocus)
     ("http://www.youtube.com/channel/UC9-y-6csu5WGm29I7JiwpnA" nonfocus)
     ("http://www.youtube.com/channel/UC8p0yf6YUxJ3IseGTYNFz0w" nonfocus)
     ("http://www.youtube.com/channel/UC8kFF39hsRrFfHM6-7A6APQ" nonfocus)
     ("http://www.youtube.com/channel/UC8cXSTGDhiZK5229zi-KTXA" nonfocus)
     ("http://www.youtube.com/channel/UC8butISFwT-Wl7EV0hUK0BQ" nonfocus)
     ("http://www.youtube.com/channel/UC8aRaZ6_0weiS50pvCmo0pw" nonfocus)
     ("http://www.youtube.com/channel/UC8Zl-NBqG4uwJm_VCxB1z9A" nonfocus)
     ("http://www.youtube.com/channel/UC8OU1Tc1kxiI37uXBAbTX7A" nonfocus)
     ("http://www.youtube.com/channel/UC8JT2m0mKEgvEtie3JNKwew" nonfocus)
     ("http://www.youtube.com/channel/UC88lvyJe7aHZmcvzvubDFRg" nonfocus)
     ("http://www.youtube.com/channel/UC80PWRj_ZU8Zu0HSMNVwKWw" nonfocus)
     ("http://www.youtube.com/channel/UC8-6kumlLiaikqLh-tdwjGA" nonfocus)
     ("http://www.youtube.com/channel/UC7kjWIK1H8tfmFlzZO-wHMw" nonfocus)
     ("http://www.youtube.com/channel/UC7_VH_kj0aD9vhuHmFheUYQ" nonfocus)
     ("http://www.youtube.com/channel/UC7IcJI8PUf5Z3zKxnZvTBog" nonfocus)
     ("http://www.youtube.com/channel/UC7DdEm33SyaTDtWYGO2CwdA" nonfocus)
     ("http://www.youtube.com/channel/UC6vQRTCxutg6fJLUGkDKynQ" nonfocus)
     ("http://www.youtube.com/channel/UC6uKrU_WqJ1R2HMTY3LIx5Q" nonfocus)
     ("http://www.youtube.com/channel/UC6oh54zIYKyW6hgBiZzLLsA" nonfocus)
     ("http://www.youtube.com/channel/UC6VkhPuCCwR_kG0GExjoozg" nonfocus)
     ("http://www.youtube.com/channel/UC6Qv9cHXwzTTAczQud_6WzA" nonfocus)
     ("http://www.youtube.com/channel/UC6H07z6zAwbHRl4Lbl0GSsw" nonfocus)
     ("http://www.youtube.com/channel/UC5g-f-g4EVRkqL8Xs888BLA" nonfocus)
     ("http://www.youtube.com/channel/UC5fFOfzgxQ9XVqNesi9U0MQ" nonfocus)
     ("http://www.youtube.com/channel/UC5_6ZD6s8klmMu9TXEB_1IA" nonfocus)
     ("http://www.youtube.com/channel/UC5WjFrtBdufl6CZojX3D8dQ" nonfocus)
     ("http://www.youtube.com/channel/UC5MaEdGrolKRJXFdXgD7RAA" nonfocus)
     ("http://www.youtube.com/channel/UC50EWznOxjXe0w4fEvm7X5Q" nonfocus)
     ("http://www.youtube.com/channel/UC4rlAVgAK0SGk-yTfe48Qpw" nonfocus)
     ("http://www.youtube.com/channel/UC4kqrkvBug_UHhPxwecxs2A" nonfocus)
     ("http://www.youtube.com/channel/UC4eyZaUKeXeFPrty1elfxzg" nonfocus)
     ("http://www.youtube.com/channel/UC4a-Gbdw7vOaccHmFo40b9g" nonfocus)
     ("http://www.youtube.com/channel/UC4WMyzBds5sSZcQxyAhxJ8g" nonfocus)
     ("http://www.youtube.com/channel/UC4UJ26WkceqONNF5S26OiVw" nonfocus)
     ("http://www.youtube.com/channel/UC4TC5LzZY8FQ_0uqm1tVukA" nonfocus)
     ("http://www.youtube.com/channel/UC4QZ_LsYcvcq7qOsOhpAX4A" nonfocus)
     ("http://www.youtube.com/channel/UC4IhgQSETRnAIEb694TwQxQ" nonfocus)
     ("http://www.youtube.com/channel/UC46vj6mN-6kZm5RYWWqebsg" nonfocus)
     ("http://www.youtube.com/channel/UC41lrNBYb9fNWnQHFyuv9wQ" nonfocus)
     ("http://www.youtube.com/channel/UC3ypnIXMFRu69CAim2QaDPw" nonfocus)
     ("http://www.youtube.com/channel/UC3fg6pL63upkXCc0T203wVg" nonfocus)
     ("http://www.youtube.com/channel/UC3YIK2Mj1oyN3V5SRQC21kw" nonfocus)
     ("http://www.youtube.com/channel/UC3VydBGBl132baPCLeDspMQ" nonfocus)
     ("http://www.youtube.com/channel/UC3ScyryU9Oy9Wse3a8OAmYQ" nonfocus)
     ("http://www.youtube.com/channel/UC3LeOpWTLFDIYz4_sgAGgkQ" nonfocus)
     ("http://www.youtube.com/channel/UC3HS6gQ79jjn4xHxogw0HiA" nonfocus)
     ("http://www.youtube.com/channel/UC34rW-HtPJulxr5wp2Xa04w" nonfocus)
     ("http://www.youtube.com/channel/UC2u0OcTDLa7hUoKD6bXL53g" nonfocus)
     ("http://www.youtube.com/channel/UC2s8JfFwmW5_CbWZjpSy_uA" nonfocus)
     ("http://www.youtube.com/channel/UC2_KC8lshtCyiLApy27raYw" nonfocus)
     ("http://www.youtube.com/channel/UC2XO4HDxzfMOZIV1l795g1Q" nonfocus)
     ("http://www.youtube.com/channel/UC2S7CBpSglY7FtwVFTckfrg" nonfocus)
     ("http://www.youtube.com/channel/UC2Cl2g2xFTZoAEldxYVzQFg" nonfocus)
     ("http://www.youtube.com/channel/UC2C_jShtL725hvbm1arSV9w" nonfocus)
     ("http://www.youtube.com/channel/UC29ju8bIPH5as8OGnQzwJyA" nonfocus)
     ("http://www.youtube.com/channel/UC22fMA3abEIXZ_ivLIqGSqA" nonfocus)
     ("http://www.youtube.com/channel/UC1Yf7IBfhSNFTIyb7v83o_g" nonfocus)
     ("http://www.youtube.com/channel/UC1RauiosDyz3K16X1wkaeiA" nonfocus)
     ("http://www.youtube.com/channel/UC1KmNKYC1l0stjctkGswl6g" nonfocus)
     ("http://www.youtube.com/channel/UC1GAhk8NbgpaTUUSw_QlkZw" nonfocus)
     ("http://www.youtube.com/channel/UC15F5t-6B3KU8YfIkFANWcQ" nonfocus)
     ("http://www.youtube.com/channel/UC0yTzhyCOykbC8LLDBDheGA" nonfocus)
     ("http://www.youtube.com/channel/UC0rqucBdTuFTjJiefW5t-IQ" nonfocus)
     ("http://www.youtube.com/channel/UC0nOQ1R3Z-vRO7K6g-W7Jkg" nonfocus)
     ("http://www.youtube.com/channel/UC0mRieuiapkSSxa4bvOswGw" nonfocus)
     ("http://www.youtube.com/channel/UC0QHWhjbe5fGJEPz3sVb6nw" nonfocus)
     ("http://www.youtube.com/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw" nonfocus)
     ("http://www.youtube.com/channel/UC-ZaFVre7Koir_VcaM2LpNA" nonfocus)
     ("http://www.youtube.com/channel/UC-Gn7EgShAINFthjuzxi9PQ" nonfocus)
     ("http://www.youtube.com/channel/UC-Fd7laaDTWM-mF478F4Kmw" nonfocus)
     ("http://www.youtube.com/channel/UC-8QAzbLcRglXeN_MY9blyw" nonfocus)
     ("http://feeds.feedburner.com/avc" nonfocus clutter)
     ("https://entrepreneurshandbook.co/feed" nonfocus clutter)
     ("https://becominghuman.ai/feed" nonfocus clutter)
     ("https://futurism.com/feed" nonfocus clutter)
     ("http://feeds.feedburner.com/sciencealert-latestnews" nonfocus clutter)
     ("https://www.entrepreneur.com/topic/marketing.rss" nonfocus clutter)
     ("https://singularityhub.com/feed" nonfocus clutter)
     ("http://feeds2.feedburner.com/TheNextWeb" nonfocus clutter)
     ("https://hnrss.org/frontpage" nonfocus clutter)
     ("https://api.quantamagazine.org/feed/" nonfocus random)
     ("http://waitbutwhy.com/feed" nonfocus random)
     ("https://jeremykun.com/feed/" nonfocus maths)
     ("https://neurosciencenews.com/feed" nonfocus neuroscience)
     ("https://simplyinvesting.com/blog.xml" focus invest)
     ("https://risknreturns.com/feed" focus invest)
     ("https://stratiphy.io/atom.xml" focus invest)
     ("https://feeds.feedburner.com/Darrensfeeds" focus invest)
     ("https://sahilbloom.substack.com/feed" focus invest)
     ("http://andrewchen.co/feed/" focus startups)
     ("https://openai.com/blog/rss" focus ml)
     ("http://feeds.feedburner.com/blogspot/gJZg" focus ml)
     ("https://medium.com/feed/@karpathy" focus ml)
     ("http://davidstutz.de/feed" focus ml)
     ("https://distill.pub/rss.xml" focus ml)
     ("https://jalammar.github.io/feed.xml" focus ml)
     ("https://blog.statsbot.co/feed" focus ml)
     ("https://blogs.princeton.edu/imabandit/feed/" focus ml)
     ("http://ruder.io/rss/index.rss" focus ml)
     ("https://www.technologyreview.com/topic/artificial-intelligence/feed" focus ml)
     ("https://machinelearningmastery.com/blog/feed/" focus ml)
     ("https://www.sciencedaily.com/rss/computers_math/artificial_intelligence" focus ml)))
 '(warning-suppress-types '((doom-first-input-hook) (defvaralias))))

;; (custom-set-faces
;;  ;; custom-set-faces was added by Custom.
;;  ;; If you edit it by hand, you could mess it up, so be careful.
;;  ;; Your init file should contain only one such instance.
;;  ;; If there is more than one, they won't work right.
;;  '(hydra-posframe-border-face ((t (:background "#6272a4"))))
;;  '(org-agenda-date ((t (:height 1.1 :background nil))))
;;  '(org-agenda-date-today ((t (:height 1.5 :background nil))))
;;  '(org-block ((t (:inherit (fixed-pitch shadow) :background nil :height 1.2))))
;;  '(org-block-begin-line ((t (:inherit region :background nil :height 0.9))))
;;  '(org-block-end-line ((t (:inherit region :background nil :height 0.8))))
;;  '(org-code ((t (:inherit (fixed-pitch shadow) :height 1.1))))
;;  '(org-document-info ((t (:foreground "dark orange"))))
;;  '(org-document-info-keyword ((t (:inherit shadow :height 0.8))))
;;  '(org-document-title ((t (:height 1.3 :weight normal :underline nil))))
;;  '(org-done ((t (:strike-through t :weight bold))))
;;  '(org-ellipsis ((t (:underline nil))))
;;  '(org-headline-done ((t (:strike-through t))))
;;  '(org-link ((t (:weight bold :height 1.1 :underline t))))
;;  '(org-meta-line ((t (:inherit (font-lock-comment-face fixed-pitch) :foreground "dark orange"))))
;;  '(org-property-value ((t (:inherit fixed-pitch))) t)
;;  '(org-special-keyword ((t (:inherit (font-lock-comment-face fixed-pitch)))))
;;  '(org-table ((t (:inherit fixed-pitch :foreground "#83a598"))))
;;  '(org-tag ((t (:inherit (shadow fixed-pitch) :weight bold :height 1.1))))
;;  '(org-verbatim ((t (:inherit shadow))))
;;  '(vterm-color-black ((t (:foreground "OrangeRed3" :background "BlueViolet"))))

;;  )

(customize-set-value
 'org-agenda-category-icon-alist
 `(
   ;; Tasks that are still not classified but will be in the future
   ("Inbox" ,(list (all-the-icons-material "check_box" :height 1.2)) nil nil :ascent center)
   ;; Reminders of dates for something important
   ("Events" ,(list (all-the-icons-material "event_note" :height 1.2)) nil nil :ascent center)
   ;; Long term tasks whose output is not immediately known
   ("ToTheMoon" ,(list (all-the-icons-octicon "rocket" :height 1.2)) nil nil :ascent center)
   ;; Short term tasks that show immediate improvements
   ("ToImprove" ,(list (all-the-icons-material "motorcycle" :height 1.2)) nil nil :ascent center)
   ;; Something I do just for the sake of doing it
   ("Hobby" ,(list (all-the-icons-material "spa" :height 1.2)) nil nil :ascent center)
   ;; Health related tasks
   ("Fitness" ,(list (all-the-icons-material "fitness_center" :height 1.2)) nil nil :ascent center)
   ;; Tasks that don't fall into any category
   ("Normal" ,(list (all-the-icons-material "computer" :height 1.2)) nil nil :ascent center)
   ;; Something that is not too valuable in terms of information
   ("Mundane" ,(list (all-the-icons-material "sentiment_dissatisfied" :height 1.2)) nil nil :ascent center)
   ;; Birthdays and Anniversaries
   ("Celebration" ,(list (all-the-icons-material "cake" :height 1.2)) nil nil :ascent center)
   ;; Birthdays and Anniversaries
   ("EHP" ,(list (all-the-icons-material "work" :height 1.2)) nil nil :ascent center)
   ;; ("recurring" ,(list (all-the-icons-material "loop" :height 1.2)) nil nil :ascent center)
   ;; ("someday" ,(list (all-the-icons-material "schedule" :height 1.2)) nil nil :ascent center)
   ;; ("project" ,(list (all-the-icons-material "stars" :height 1.2)) nil nil :ascent center)
   ;; ("reading" ,(list (all-the-icons-material "book" :height 1.2)) nil nil :ascent center)
   ;; ("coding" ,(list (all-the-icons-material "code" :height 1.2)) nil nil :ascent center)
   ;; Based on purpose
   ;; ("hobby" ,(list (all-the-icons-material "gamepad" :height 1.2)) nil nil :ascent center)
   ;; ("finance" ,(list (all-the-icons-material "attach_money" :height 1.2)) nil nil :ascent center)
   ;; ("skill" ,(list (all-the-icons-material "directions_bike" :height 1.2)) nil nil :ascent center)
   ;; ("relax" ,(list (all-the-icons-material "ondemand_video" :height 1.2)) nil nil :ascent center)
   ;; ("research" ,(list (all-the-icons-material "explore" :height 1.2)) nil nil :ascent center)
   ;; ("fitness" ,(list (all-the-icons-material "spa" :height 1.2)) nil nil :ascent center)
   ;; ("daytoday" ,(list (all-the-icons-material "local_grocery_store" :height 1.2)) nil nil :ascent center)
   ;; ("feedback" ,(list (all-the-icons-material "loop" :height 1.2)) nil nil :ascent center)
   ;; ;; Things that get excluded from the list of purpose
   ;; ("events" ,(list (all-the-icons-material "event" :height 1.2)) nil nil :ascent center)
   ;; ("inbox" ,(list (all-the-icons-material "check_box" :height 1.2)) nil nil :ascent center)
   ;; ("necessity" ,(list (all-the-icons-material "hourglass_full" :height 1.2)) nil nil :ascent center)
   ;;
   ;; ("office" ,(list (all-the-icons-material "work" :height 1.2)) nil nil :ascent center)
   ;; ("mundane" ,(list (all-the-icons-material "weekend" :height 1.2)) nil nil :ascent center)
   ;; ("emacs" ,(list (all-the-icons-material "format_paint" :height 1.2)) nil nil :ascent center)
   ;; ("tinker" ,(list (all-the-icons-material "build" :height 1.2)) nil nil :ascent center)
   ;; ("freelance" ,(list (all-the-icons-material "redeem" :height 1.2)) nil nil :ascent center)
   ;; ("book" ,(list (all-the-icons-material "book" :height 1.2)) nil nil :ascent center)
   ))

(customize-set-value
 'org-fancy-priorities-list
 `(
   (?A ,(concat " " (all-the-icons-octicon "pulse" :height 1.2) " "))
   (?B ,(concat " " (all-the-icons-octicon "mortar-board" :height 1.2) " "))
   (?C ,(concat " " (all-the-icons-octicon "flame" :height 1.2) " "))
   (?D ,(concat " " (all-the-icons-octicon "telescope" :height 1.2) " "))
   ))

(customize-set-value
 'org-priority-faces
 `(
   (?A . (:foreground "red" :weight bold))
   (?B . (:foreground "green" :weight bold))
   (?C . (:foreground "tomato"))
   (?D . (:foreground "orange"))
   )
 )
(put 'narrow-to-region 'disabled nil)
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(blamer-face ((t :foreground "#7a88cf" :background nil :height 140 :italic t)))
 '(hydra-posframe-border-face ((t (:background "#6272a4"))))
 '(ts-fold-replacement-face ((t (:foreground nil :box nil :inherit font-lock-comment-face :weight light))))
 '(vterm-color-black ((t (:foreground "OrangeRed3" :background "BlueViolet")))))
